#+title: Literate Emacs configuration with Org mode
#+subtitle: General overview
#+author: Ryan Matlock

* Motivation
In 2021, I decided that my 1700+ line ~.emacs~ file, parts of which dated to
2014, was becoming too difficult to maintain. An Org mode-based set of
configuration files seemed much easier to manage, and [[https://github.com/radian-software/straight.el][straight.el]] has made the
process of syncing configurations across devices even simpler.

* Usage
** Escape hatch
In case you need to go back to your old configuration:

#+begin_src sh :eval no
  ln -s /path/to/legacy-dotemacs.el ~/.emacs
#+end_src

Then either reload =.emacs= or restart Emacs. Looks like you shouldn't need to do
this though.

** TODO How this works -- correct this
=.emacs= is symlinked to =dotemacs.el=, which loads the necessary +~package~+ and
~use-package~ packages in order for ~org-babel-load-file~ to process this file,
+=README.org=+, which contains all the Emacs Lisp configuration goodness (excluding
the stuff handled by ~customize-variable~).

** Configuration organization

*** ~core-config.org~
Also includes main editing commands for
- Org mode (but not Org-roam)
- Emacs Lisp
- git
so that this file can be easily edited without loading additional extensions.

*** ~core-langs.org~
Includes configuration for
- LSP mode
- Haskell
- Python
- Rust
- TeX/LaTeX/AUCTeX

*** ~extras.org~
- Org roam
- markdown
- minor modes
- highly specific/project-oriented extensions
